"""empty message

Revision ID: 96148c380965
Revises: 
Create Date: 2022-11-23 18:34:47.286310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96148c380965'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('email', sa.String(length=50, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('phone', sa.String(length=20, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    # ### end Alembic commands ###
